<meta name="google-site-verification" content="4BqhmS-A4SsMKCB8ZeAT68K7_6A3_54Mtzt4VYJ_zOY" />

title: Jean Barbier
logo: /assets/img/UNADJUSTEDNONRAW_thumb_5747.jpg
description: Mathematical Physics of Information Processing Systems
theme: jekyll-theme-minimal
